version: "2"

services:
  todoserver:
    build: ./
    image: todoserver-grpc
    command: sh -c '/server'
    ports:
      - 5000:5000
    environment:
      - "STATSD=statsd:9125"
    links:
      - statsd
  statsd:
    image: prom/statsd-exporter
  prometheus:
    image: prom/prometheus
    links:
      - statsd
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  graphana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
